name: Build manager

on: [ workflow_dispatch ]

jobs:
  build-on-macos:
    name: Build on macOS
    runs-on: macos-13
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
      - name: Check out code
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - name: Build
        run: node ./scripts/build.js
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: manager-macos
          path: ${{ github.workspace }}/manager/out/make/zip/darwin/x64
  build-on-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Check out code
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - name: Build
        run: node ./scripts/build.js
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: manager-windows
          path: ${{ github.workspace }}/manager/out/make/zip/win32/x64
